name: lr_igv
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base>=4.3
  - r-dplyr
  - r-tidyr
  - r-readr
  - bioconductor-rtracklayer
  - bioconductor-genomicranges
  - bioconductor-edger
  - bioconductor-biostrings
  - htslib>=1.15
  - samtools>=1.15
